/* Food Trucks database construction */

CREATE DATABASE FoodTrucks
GO

USE FoodTrucks
GO

/* creating tables */

CREATE TABLE tblTruck (
	TruckID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	CompanyID INT NOT NULL,
	LocationID INT NOT NULL,
	MenuID INT NOT NULL
)
GO

CREATE TABLE tblAppliance_Truck(
	Appliance_TruckID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	ApplianceTypeID INT NOT NULL,
	TruckID INT NOT NULL,
	DateInstalled DATE NOT NULL
)
GO

CREATE TABLE tblApplianceType(
	ApplianceTypeID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	ApplianceName VARCHAR(50) NOT NULL,
	ApplianceDescription VARCHAR(100) NOT NULL
)
GO

CREATE TABLE tblTruck_Location(
	Truck_LocationID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	TruckID INT NOT NULL,
	LocationID INT NOT NULL
)

CREATE TABLE tblLocation(
	LocationID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	StreetAddress VARCHAR(50) NOT NULL,
	Zip INT NOT NULL,
	LocationName VARCHAR(50) NOT NULL
)
GO

CREATE TABLE tblLocation_Name(
	LocationNameID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	LocationDescription VARCHAR(100) NOT NULL
)
GO

CREATE TABLE tblCompany(
	CompanyID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	CompanyName VARCHAR(50) NOT NULL,
	CompanyDescription VARCHAR(100) NOT NULL
)

CREATE TABLE tblMenu(
	MenuID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	Menu_TypeID INT NOT NULL,
	MenuName VARCHAR(50) NOT NULL
)
GO

CREATE TABLE tblMenu_Type(
	Menu_TypeID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	Menu_TypeName VARCHAR(50) NOT NULL,
	Menu_TypeDescription VARCHAR(100) NOT NULL
)
GO

CREATE TABLE tblMenuItem(
	MenuItemID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	MenuID INT NOT NULL,
	MenuItemName VARCHAR(50) NOT NULL
)
GO

CREATE TABLE tblMenuItem_Ingredient(
	MenuItem_IngredientID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	MenuItemID INT NOT NULL,
	IngredientID INT NOT NULL,
	Quantity INT NOT NULL,
	Calories INT NOT NULL
)
GO

CREATE TABLE tblIngredient(
	IngredientID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	SupplierID INT NOT NULL,
	IngredientDescription VARCHAR(100) NOT NULL
)
GO

CREATE TABLE tblSupplier(
	SupplierID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	SupplierName VARCHAR(50) NOT NULL,
	SupplierDescription VARCHAR(100) NOT NULL,
)
GO

CREATE TABLE tblOrder(
	OrderID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	MenuID INT NOT NULL,
	CustomerID INT NOT NULL,
	OrderDate DATE NOT NULL
)
GO

CREATE TABLE tblCustomer(
	CustomerID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	Fname VARCHAR(50) NOT NULL,
	LName VARCHAR(50) NOT NULL,
	DOB DATE NOT NULL
)
GO

CREATE TABLE tblEmployee(
	EmployeeID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	TruckID INT NOT NULL,
	PositionID INT NOT NULL,
	FName VARCHAR(50) NOT NULL,
	LName VARCHAR(50) NOT NULL,
	DOB DATE NOT NULL
)
GO

CREATE TABLE tblPosition(
	PositionID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	PositionName VARCHAR(50) NOT NULL,
	PositionDescription VARCHAR(100) NOT NULL
)GO

/* adding FKs */