/* Food Trucks database construction */

CREATE DATABASE FoodTrucks1
GO

USE FoodTrucks1
GO

/* creating tables */

CREATE TABLE tblTruck (
	TruckID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	CompanyID INT NOT NULL,
	MenuID INT NOT NULL
)
GO

CREATE TABLE tblAppliance_Truck(
	Appliance_TruckID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	ApplianceTypeID INT NOT NULL,
	TruckID INT NOT NULL,
	DateInstalled DATE NOT NULL
)
GO

CREATE TABLE tblApplianceType(
	ApplianceTypeID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	ApplianceName VARCHAR(50) NOT NULL,
	ApplianceDescription VARCHAR(100) NOT NULL
)
GO

CREATE TABLE tblTruck_Location(
	Truck_LocationID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	TruckID INT NOT NULL,
	LocationID INT NOT NULL
)

CREATE TABLE tblLocation(
	LocationID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	Location_NameID INT NOT NULL,
	StreetAddress VARCHAR(50) NOT NULL,
	Zip INT NOT NULL
)
GO

CREATE TABLE tblLocation_Name(
	Location_NameID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	LocationDescription VARCHAR(100) NOT NULL
)
GO

CREATE TABLE tblCompany(
	CompanyID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	CompanyName VARCHAR(50) NOT NULL,
	CompanyDescription VARCHAR(100) NOT NULL
)

CREATE TABLE tblMenu(
	MenuID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	Menu_TypeID INT NOT NULL,
	MenuName VARCHAR(50) NOT NULL
)
GO

CREATE TABLE tblMenu_Type(
	Menu_TypeID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	Menu_TypeName VARCHAR(50) NOT NULL,
	Menu_TypeDescription VARCHAR(100) NOT NULL
)
GO

CREATE TABLE tblMenuItem(
	MenuItemID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	MenuID INT NOT NULL,
	MenuItemName VARCHAR(50) NOT NULL
)
GO

CREATE TABLE tblMenuItem_Ingredient(
	MenuItem_IngredientID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	MenuItemID INT NOT NULL,
	IngredientID INT NOT NULL,
	Quantity INT NOT NULL,
	Calories INT NOT NULL
)
GO

CREATE TABLE tblIngredient(
	IngredientID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	SupplierID INT NOT NULL,
	IngredientDescription VARCHAR(100) NOT NULL
)
GO

ALTER TABLE tblIngredient
	ADD IngredientName VARCHAR(50) NOT NULL
go

CREATE TABLE tblSupplier(
	SupplierID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	SupplierName VARCHAR(50) NOT NULL,
	SupplierDescription VARCHAR(100) NOT NULL,
)
GO

CREATE TABLE tblOrder(
	OrderID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	MenuID INT NOT NULL,
	CustomerID INT NOT NULL,
	OrderDate DATE NOT NULL
)
GO

CREATE TABLE tblCustomer(
	CustomerID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	Fname VARCHAR(50) NOT NULL,
	LName VARCHAR(50) NOT NULL,
	DOB DATE NOT NULL
)
GO

CREATE TABLE tblEmployee(
	EmployeeID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	TruckID INT NOT NULL,
	PositionID INT NOT NULL,
	FName VARCHAR(50) NOT NULL,
	LName VARCHAR(50) NOT NULL,
	DOB DATE NOT NULL
)
GO

CREATE TABLE tblPosition(
	PositionID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	PositionName VARCHAR(50) NOT NULL,
	PositionDescription VARCHAR(100) NOT NULL
)
GO

/* adding FKs */

ALTER TABLE tblTruck
ADD CONSTRAINT FK_CompanyID
FOREIGN KEY (CompanyID)
REFERENCES tblCompany (CompanyID)
GO

ALTER TABLE tblTruck
ADD CONSTRAINT FK_MenuID
FOREIGN KEY (MenuID)
REFERENCES tblMenu (MenuID)
GO

ALTER TABLE tblAppliance_Truck
ADD CONSTRAINT FK_ApplianceType
FOREIGN KEY (ApplianceTypeID)sfd
REFERENCES tblApplianceType (ApplianceTypeID)
GO

ALTER TABLE tblAppliance_Truck
ADD CONSTRAINT FK_TruckID
FOREIGN KEY (TruckID)
REFERENCES tblTruck (TruckID)
GO

ALTER TABLE tblTruck_Location
ADD CONSTRAINT FK_Truck
FOREIGN KEY (TruckID)
REFERENCES tblTruck (TruckID)
GO

ALTER TABLE tblLocation
ADD CONSTRAINT FK_Location_Name
FOREIGN KEY (Location_NameID)
REFERENCES tblLocation_Name (Location_NameID)
GO

ALTER TABLE tblTruck_Location
ADD CONSTRAINT FK_Location
FOREIGN KEY (LocationID)
REFERENCES tblLocation (LocationID)
GO

ALTER TABLE tblMenu
ADD CONSTRAINT FK_Menu_Type
FOREIGN KEY (Menu_TypeID)
REFERENCES tblMenu_Type (Menu_TypeID)
GO

ALTER TABLE tblMenuItem
ADD CONSTRAINT FK_Menu
FOREIGN KEY (MenuID)
REFERENCES tblMenu (MenuID)
GO

ALTER TABLE tblMenuItem_Ingredient
ADD CONSTRAINT FK_MenuItem
FOREIGN KEY (MenuItemID)
REFERENCES tblMenuItem (MenuItemID)
GO

ALTER TABLE tblMenuItem_Ingredient
ADD CONSTRAINT FK_Ingredient
FOREIGN KEY (IngredientID)
REFERENCES tblIngredient (IngredientID)
GO

ALTER TABLE tblIngredient
ADD CONSTRAINT FK_Supplier
FOREIGN KEY (SupplierID)
REFERENCES tblSupplier (SupplierID)
GO

ALTER TABLE tblOrder
ADD CONSTRAINT FK_Menu1
FOREIGN KEY (MenuID)
REFERENCES tblMenu (MenuID)
GO

ALTER TABLE tblOrder
ADD CONSTRAINT FK_Customer
FOREIGN KEY (CustomerID)
REFERENCES tblCustomer (CustomerID)
GO

ALTER TABLE tblEmployee
ADD CONSTRAINT FK_Truck1
FOREIGN KEY (TruckID)
REFERENCES tblTruck (TruckID)
GO

ALTER TABLE tblEmployee
ADD CONSTRAINT FK_Position
FOREIGN KEY (PositionID)
REFERENCES tblPosition (PositionID)
GO
